"""Initial migration

Revision ID: 5bf0a5d0ef9c
Revises:
Create Date: 2026-01-17 18:46:53.388007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf0a5d0ef9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pricerecords',
        sa.Column(
            'ticker',
            sa.String(length=20),
            nullable=False
        ),
        sa.Column(
            'price',
            sa.DECIMAL(
                precision=20,
                scale=8
            ),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Время создания записи'
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
            comment='Время последнего обновления'
        ),
        sa.Column(
            'id',
            sa.UUID(as_uuid=True),
            nullable=False,
            comment='Уникальный идентификатор'
        ),
        sa.Column(
            'timestamp',
            sa.BigInteger(),
            nullable=False,
            comment='UNIX timestamp цены'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_pricerecords_id'),
        'pricerecords',
        ['id'],
        unique=False
    )
    op.create_index(
        op.f('ix_pricerecords_ticker'),
        'pricerecords',
        ['ticker'],
        unique=False
    )
    op.create_index(
        op.f('ix_pricerecords_timestamp'),
        'pricerecords',
        ['timestamp'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_pricerecords_timestamp'),
        table_name='pricerecords'
    )
    op.drop_index(
        op.f('ix_pricerecords_ticker'),
        table_name='pricerecords'
    )
    op.drop_index(
        op.f('ix_pricerecords_id'),
        table_name='pricerecords'
    )
    op.drop_table('pricerecords')
    # ### end Alembic commands ###
